# Project information
site_name:        'StableFill'
site_description: 'Update LaTeX, LyX, and Markdown tables and inline values'

# Repository
repo_name: 'avvorstenbosch/StableFill'
repo_url: 'https://github.com/avvorstenbosch/StableFill'
edit_uri: 'blob/master/docs/'
site_url: 'https://avvorstenbosch.github.io/StableFill/'

nav:
    - Home: index.md
    - Getting Started:    getting-started.md
    - Usage:
        - Matrix Input:     usage/02matrix-input.md
        - Placeholders:     usage/03placeholders.md
        - Inline Values:    usage/07-inline-values.md
        - LaTeX Economics:  usage/08-latex-economics.md
        - Diagnostics and Testing: usage/09-diagnostics-testing.md
        - Annotation Mode:  usage/10-annotations.md

theme:
    name: 'material'
    palette:
        primary: 'blue grey'
        accent: 'blue grey'
    font:
        text: 'Open Sans'
        code: 'Inconsolata'

markdown_extensions:
    - meta
    - toc
    - tables
    - fenced_code
    - admonition
    - codehilite:
        guess_lang: false

use_directory_urls: false
